#!/usr/bin/env python3
"""
Compare baseline Endocrine metabolomics mortality EPOCH clocks trained with
5-year, 10-year, and full available mortality follow-up for prediction of
incident major diseases.

Primary design
--------------
1. Read the three baseline Endocrine EPOCH acceleration scores generated by
   endocrine_metabolomics_horizon_clocks.py:

     endocrine_metabolomics_mortality_clock_acceleration_z_5y
     endocrine_metabolomics_mortality_clock_acceleration_z_10y
     endocrine_metabolomics_mortality_clock_acceleration_z_full

2. Use baseline assessment/sample date as time zero.
3. Exclude disease events on or before baseline for the endpoint being tested.
4. Censor at the earlier of death or the administrative censor date.
5. Fit the SAME common disease cohort for all three horizon-specific clocks.
6. For each clock, fit:

     Cox(time to disease/censor) ~ common covariates + EPOCH_horizon

   and compare it with the same covariate-only model.
7. Report HR per 1 SD higher EPOCH, 95% CI, Wald P value, likelihood-ratio
   test versus the covariate-only model, Harrell C-index, and incremental C.
8. Compare the three horizon-specific full-model C-indices by paired
   participant bootstrap using fixed fitted-model risk predictions.

By default, the primary analysis uses only participants assigned to the held-out
"test" split during mortality-EPOCH development. This avoids reusing the
mortality-clock training/validation participants for downstream disease
prediction. Set --analysis_split all for a larger sensitivity analysis.
"""

import argparse
import json
import os
import re
import warnings
from itertools import combinations
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index
from scipy.stats import chi2

warnings.filterwarnings("ignore")


ENDPOINTS: Dict[str, Dict[str, str]] = {
    "all_cause_dementia": {
        "label": "All-cause dementia",
        "date_field": "42018",
        "source_field": "42019",
    },
    "asthma": {
        "label": "Asthma",
        "date_field": "42014",
        "source_field": "42015",
    },
    "myocardial_infarction": {
        "label": "Myocardial infarction",
        "date_field": "42000",
        "source_field": "42001",
    },
    "copd": {
        "label": "COPD",
        "date_field": "42016",
        "source_field": "42017",
    },
    "stroke": {
        "label": "Stroke",
        "date_field": "42006",
        "source_field": "42007",
    },
}

DEATH_FIELD = "40000"

CLOCK_COLUMNS = {
    "5y": "endocrine_metabolomics_mortality_clock_acceleration_z_5y",
    "10y": "endocrine_metabolomics_mortality_clock_acceleration_z_10y",
    "full": "endocrine_metabolomics_mortality_clock_acceleration_z_full",
}
HORIZON_ORDER = ["5y", "10y", "full"]

AGE_RECRUIT_COL = "age_at_recruitment_f21022_0_0"
SMOKING_COL = "smoking_status_f20116_0_0"
BMI_COL = "body_mass_index_bmi_f23104_0_0"
DIASTOLIC_COL = "diastolic_blood_pressure_automated_reading_f4079_0_0"
SYSTOLIC_COL = "systolic_blood_pressure_automated_reading_f4080_0_0"

DEFAULT_HORIZON_PREDICTIONS = (
    "/cbica/home/wenju/Reproducibile_paper/WholeBodyClock/"
    "Endocrine_metabolomics_mortality_horizon_clocks/"
    "endocrine_metabolomics_mortality_horizon_clocks_predictions.tsv"
)


def parse_args():
    p = argparse.ArgumentParser(
        description=(
            "Compare 5y/10y/full baseline Endocrine metabolomics mortality EPOCH "
            "clocks for incident algorithmically-defined disease onset."
        )
    )
    p.add_argument("--endpoint", required=True, choices=sorted(ENDPOINTS.keys()))
    p.add_argument("--output_tsv", required=True)
    p.add_argument("--horizon_predictions", default=DEFAULT_HORIZON_PREDICTIONS)
    p.add_argument(
        "--analysis_split",
        default="test",
        choices=["test", "all"],
        help=(
            "Primary default is 'test': only the held-out mortality-clock test split. "
            "Use 'all' as a larger sensitivity analysis."
        ),
    )
    p.add_argument(
        "--umel_death_xlsx",
        default="/cbica/home/wenju/Dataset/UKBB_UMelbourne/Death_related_var_from_Ye.xlsx",
    )
    p.add_argument(
        "--umel_match_csv",
        default="/cbica/home/wenju/Dataset/UKBB_UMelbourne/UKB_UMelbourne_vs_Penn_match_key.csv",
    )
    p.add_argument(
        "--cov_tsv",
        default=(
            "/cbica/home/wenju/Reproducibile_paper/PRS_UKBB/prediction/data/"
            "UKBB_fullsample_covariate.csv"
        ),
    )
    p.add_argument("--admin_censor_date", default="2022-11-30")
    p.add_argument("--min_case", type=int, default=20)
    p.add_argument("--min_noncase", type=int, default=20)
    p.add_argument("--penalizer", type=float, default=0.0)
    p.add_argument(
        "--include_bp",
        action="store_true",
        help="Include baseline diastolic and systolic blood pressure covariates.",
    )
    p.add_argument("--n_bootstrap", type=int, default=1000)
    p.add_argument("--random_state", type=int, default=2026)
    p.add_argument("--no_plot", action="store_true")
    p.add_argument(
        "--no_save_analysis_dataset",
        action="store_true",
        help="Do not save the participant-level endpoint analysis dataset.",
    )
    return p.parse_args()


def normalize_participant_id(df: pd.DataFrame, col: str = "participant_id") -> pd.DataFrame:
    if col not in df.columns:
        raise ValueError(f"Missing ID column: {col}")
    out = df.copy()
    out[col] = pd.to_numeric(out[col], errors="coerce").astype("Int64")
    out = out.loc[out[col].notna()].copy()
    out[col] = out[col].astype(int)
    return out


def parse_ukb_date(series: pd.Series) -> pd.Series:
    x = series.copy()
    x = x.replace(
        [0, 0.0, "0", "0.0", "", "NA", "NaN", "nan", "None", "-1", -1],
        np.nan,
    )
    parsed = pd.to_datetime(x, errors="coerce")

    numeric = pd.to_numeric(x, errors="coerce")
    excel_mask = numeric.between(20000, 60000)
    if excel_mask.any():
        excel_dates = pd.to_datetime(
            numeric, unit="D", origin="1899-12-30", errors="coerce"
        )
        parsed = parsed.where(~excel_mask, excel_dates)
    return parsed


def find_ukb_field_column(df: pd.DataFrame, field_id: str, required: bool = True) -> str:
    field_id = str(field_id)
    col_str = {c: str(c) for c in df.columns}

    exact_candidates = [
        field_id,
        f"{field_id}-0.0",
        f"{field_id}_0_0",
        f"f{field_id}",
        f"f{field_id}_0_0",
    ]
    for wanted in exact_candidates:
        for c, s in col_str.items():
            if s == wanted:
                return c

    patterns = [
        rf"(^|[^0-9]){re.escape(field_id)}([^0-9]|$)",
        rf"f{re.escape(field_id)}(_|$)",
    ]
    matches = []
    for c, s in col_str.items():
        for pat in patterns:
            if re.search(pat, s):
                matches.append(c)
                break

    if matches:
        for c in matches:
            s = str(c)
            if s.endswith("-0.0") or s.endswith("_0_0"):
                return c
        return matches[0]

    if required:
        preview = ", ".join(list(map(str, df.columns[:40])))
        raise ValueError(f"Could not find UKB field {field_id}. First columns: {preview}")
    return ""


def read_algorithmic_outcome_dates(args) -> pd.DataFrame:
    info = ENDPOINTS[args.endpoint]
    if not os.path.exists(args.umel_death_xlsx):
        raise FileNotFoundError(args.umel_death_xlsx)
    if not os.path.exists(args.umel_match_csv):
        raise FileNotFoundError(args.umel_match_csv)

    raw = pd.read_excel(args.umel_death_xlsx, engine="openpyxl")
    match = pd.read_csv(args.umel_match_csv)

    if "eid" not in raw.columns:
        raise ValueError("UMelbourne Excel file must contain eid.")
    if not all(c in match.columns for c in ["id", "id_upenn"]):
        raise ValueError("ID match CSV must contain id and id_upenn.")

    disease_col = find_ukb_field_column(raw, info["date_field"], required=True)
    source_col = find_ukb_field_column(raw, info["source_field"], required=False)
    death_col = find_ukb_field_column(raw, DEATH_FIELD, required=False)

    raw = raw.rename(columns={"eid": "participant_id_umel"})
    match = match.rename(columns={"id": "participant_id_umel", "id_upenn": "participant_id"})
    raw = normalize_participant_id(raw, "participant_id_umel")
    match = normalize_participant_id(match, "participant_id_umel")
    match = normalize_participant_id(match, "participant_id")

    keep = ["participant_id_umel", disease_col]
    if source_col:
        keep.append(source_col)
    if death_col:
        keep.append(death_col)

    d = match[["participant_id_umel", "participant_id"]].merge(
        raw[keep], on="participant_id_umel", how="inner"
    )

    out = pd.DataFrame({"participant_id": d["participant_id"].values})
    out["event_date_raw"] = d[disease_col].values
    out["event_date"] = parse_ukb_date(d[disease_col])
    out["event_source"] = d[source_col].values if source_col else np.nan
    out["death_date_algorithmic_file"] = (
        parse_ukb_date(d[death_col]) if death_col else pd.NaT
    )
    out["endpoint"] = args.endpoint
    out["endpoint_label"] = info["label"]
    out["endpoint_date_field"] = info["date_field"]
    out["endpoint_source_field"] = info["source_field"]

    return (
        out.sort_values("participant_id")
        .groupby("participant_id", as_index=False)
        .first()
    )


def coerce_sex_numeric(series: pd.Series) -> pd.Series:
    numeric = pd.to_numeric(series, errors="coerce")
    if numeric.notna().sum() > 0:
        return numeric
    s = series.astype(str).str.strip().str.lower()
    return s.map({"female": 0.0, "f": 0.0, "male": 1.0, "m": 1.0})


def read_covariates(path: str, include_bp: bool) -> pd.DataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    cov_all = pd.read_csv(path)
    if "eid" not in cov_all.columns and "participant_id" not in cov_all.columns:
        raise ValueError("Covariate file must contain eid or participant_id.")
    if "eid" in cov_all.columns:
        cov_all = cov_all.rename(columns={"eid": "participant_id"})

    sex_candidates = ["sex_f31_0_0", "genetic_sex_f22001_0_0", "Sex", "sex"]
    sex_col = next((c for c in sex_candidates if c in cov_all.columns), None)

    keep = ["participant_id"]
    rename = {}
    for src, dst in [
        (AGE_RECRUIT_COL, "Age_recruitment_fallback"),
        (SMOKING_COL, "Smoking"),
        (BMI_COL, "BMI"),
        (sex_col, "Sex"),
    ]:
        if src is not None and src in cov_all.columns:
            keep.append(src)
            rename[src] = dst

    if include_bp:
        for src, dst in [
            (DIASTOLIC_COL, "Diastolic"),
            (SYSTOLIC_COL, "Systolic"),
        ]:
            if src in cov_all.columns:
                keep.append(src)
                rename[src] = dst

    cov = cov_all[keep].copy().rename(columns=rename)
    cov = normalize_participant_id(cov, "participant_id")

    if "Sex" in cov.columns:
        cov["Sex"] = coerce_sex_numeric(cov["Sex"])
    for c in cov.columns:
        if c in {"participant_id", "Sex"}:
            continue
        cov[c] = pd.to_numeric(cov[c], errors="coerce")

    return cov.drop_duplicates("participant_id", keep="first")


def read_horizon_clocks(path: str, analysis_split: str) -> pd.DataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    df = pd.read_csv(path, sep="\t")
    df = normalize_participant_id(df, "participant_id")

    required = ["participant_id", "sample_date", "split"] + list(CLOCK_COLUMNS.values())
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Horizon prediction file is missing columns: {missing}")

    keep = [
        "participant_id",
        "baseline_date" if "baseline_date" in df.columns else None,
        "sample_date",
        "death_date" if "death_date" in df.columns else None,
        "admin_censor_date" if "admin_censor_date" in df.columns else None,
        "age_at_baseline" if "age_at_baseline" in df.columns else None,
        "split",
    ] + list(CLOCK_COLUMNS.values())
    keep = [c for c in keep if c is not None]
    df = df[keep].copy()

    if analysis_split == "test":
        before = df.shape[0]
        df = df.loc[df["split"].astype(str).str.lower() == "test"].copy()
        print(f"Filtered horizon clock predictions to held-out test split: {before} -> {df.shape[0]}")
    else:
        print(f"Using all available horizon clock predictions: N={df.shape[0]}")

    df["sample_date"] = parse_ukb_date(df["sample_date"])
    if "baseline_date" in df.columns:
        df["baseline_date"] = parse_ukb_date(df["baseline_date"])
        df["sample_date"] = df["sample_date"].where(df["sample_date"].notna(), df["baseline_date"])
    if "death_date" in df.columns:
        df["death_date"] = parse_ukb_date(df["death_date"])
    if "admin_censor_date" in df.columns:
        df["admin_censor_date"] = parse_ukb_date(df["admin_censor_date"])
    if "age_at_baseline" in df.columns:
        df["age_at_baseline"] = pd.to_numeric(df["age_at_baseline"], errors="coerce")

    for c in CLOCK_COLUMNS.values():
        df[c] = pd.to_numeric(df[c], errors="coerce")

    return df.drop_duplicates("participant_id", keep="first")


def prepare_survival_dataset(args) -> pd.DataFrame:
    clocks = read_horizon_clocks(args.horizon_predictions, args.analysis_split)
    outcome = read_algorithmic_outcome_dates(args)
    cov = read_covariates(args.cov_tsv, args.include_bp)

    data = clocks.merge(outcome, on="participant_id", how="left")
    data = data.merge(cov, on="participant_id", how="left")

    data["sample_date"] = parse_ukb_date(data["sample_date"])
    data["event_date"] = parse_ukb_date(data["event_date"])
    data["death_date_algorithmic_file"] = parse_ukb_date(data["death_date_algorithmic_file"])
    if "death_date" in data.columns:
        data["death_date"] = parse_ukb_date(data["death_date"])
    else:
        data["death_date"] = pd.NaT

    admin_const = pd.Timestamp(args.admin_censor_date)
    if "admin_censor_date" in data.columns:
        data["admin_censor_date"] = parse_ukb_date(data["admin_censor_date"])
        data["admin_censor_date"] = data["admin_censor_date"].where(
            data["admin_censor_date"].notna(), admin_const
        )
    else:
        data["admin_censor_date"] = admin_const

    data["death_censor_date"] = data["death_date_algorithmic_file"].where(
        data["death_date_algorithmic_file"].notna(), data["death_date"]
    )

    # Use the earlier of death and administrative censoring.
    data["censor_date"] = data["admin_censor_date"]
    death_before_admin = (
        data["death_censor_date"].notna()
        & (data["death_censor_date"] < data["admin_censor_date"])
    )
    data.loc[death_before_admin, "censor_date"] = data.loc[
        death_before_admin, "death_censor_date"
    ]

    # Disease present at or before baseline is excluded from incident-disease analyses.
    data["prevalent_or_prior_to_baseline"] = (
        data["event_date"].notna()
        & data["sample_date"].notna()
        & (data["event_date"] <= data["sample_date"])
    ).astype(int)

    data["incident_event_after_baseline"] = (
        data["event_date"].notna()
        & data["sample_date"].notna()
        & (data["event_date"] > data["sample_date"])
        & (data["event_date"] <= data["censor_date"])
    ).astype(int)

    data["end_date_disease"] = data["censor_date"]
    event_mask = data["incident_event_after_baseline"] == 1
    data.loc[event_mask, "end_date_disease"] = data.loc[event_mask, "event_date"]

    data["time_from_baseline_to_disease_or_censor_days"] = (
        data["end_date_disease"] - data["sample_date"]
    ).dt.days
    data["time_from_baseline_to_disease_or_censor_years"] = (
        data["time_from_baseline_to_disease_or_censor_days"] / 365.25
    )
    data["disease_case"] = data["incident_event_after_baseline"].astype(int)
    data["endpoint"] = args.endpoint
    data["endpoint_label"] = ENDPOINTS[args.endpoint]["label"]
    data["analysis_split"] = args.analysis_split

    # Prefer the exact baseline age carried with the EPOCH prediction file.
    if "age_at_baseline" in data.columns:
        data["Age_baseline"] = pd.to_numeric(data["age_at_baseline"], errors="coerce")
    else:
        data["Age_baseline"] = np.nan
    if "Age_recruitment_fallback" in data.columns:
        data["Age_baseline"] = data["Age_baseline"].where(
            data["Age_baseline"].notna(),
            pd.to_numeric(data["Age_recruitment_fallback"], errors="coerce"),
        )

    return data


def base_covariates(df: pd.DataFrame, include_bp: bool) -> List[str]:
    candidates = ["Age_baseline", "Sex", "Smoking", "BMI"]
    if include_bp:
        candidates.extend(["Diastolic", "Systolic"])

    covars = []
    for c in candidates:
        if c not in df.columns:
            continue
        vals = pd.to_numeric(df[c], errors="coerce")
        if vals.notna().sum() > 0 and vals.nunique(dropna=True) > 1:
            df[c] = vals
            covars.append(c)
    return covars


def standardize_on_common_pool(values: pd.Series) -> Tuple[pd.Series, float, float]:
    x = pd.to_numeric(values, errors="coerce")
    mean = float(x.mean())
    sd = float(x.std(ddof=1))
    if not np.isfinite(sd) or sd <= 0:
        return pd.Series(np.nan, index=x.index), mean, sd
    return (x - mean) / sd, mean, sd


def fit_cox(
    df: pd.DataFrame,
    time_col: str,
    event_col: str,
    predictors: List[str],
    penalizer: float,
):
    cols = [time_col, event_col] + predictors
    fit_df = df[cols].copy()
    for c in cols:
        fit_df[c] = pd.to_numeric(fit_df[c], errors="coerce")
    fit_df = fit_df.replace([np.inf, -np.inf], np.nan).dropna().copy()
    fit_df = fit_df.loc[fit_df[time_col] > 0].copy()

    usable = []
    for c in predictors:
        if fit_df[c].nunique(dropna=True) > 1:
            usable.append(c)
    fit_df = fit_df[[time_col, event_col] + usable].copy()

    if int(fit_df[event_col].sum()) == 0 or int((fit_df[event_col] == 0).sum()) == 0:
        raise ValueError("No cases or no non-cases in complete-case fit_df.")

    penalties = []
    for pen in [penalizer, 0.001, 0.01, 0.1]:
        if pen not in penalties:
            penalties.append(pen)

    last_error = None
    for pen in penalties:
        try:
            cph = CoxPHFitter(penalizer=pen)
            cph.fit(
                fit_df,
                duration_col=time_col,
                event_col=event_col,
                show_progress=False,
            )
            return cph, fit_df, usable, pen
        except Exception as exc:
            last_error = exc
    raise last_error


def extract_hr(cph: CoxPHFitter, var: str) -> Dict[str, float]:
    beta = float(cph.params_.loc[var])
    se = float(cph.standard_errors_.loc[var])
    return {
        "beta": beta,
        "se": se,
        "hr": float(np.exp(beta)),
        "ci_lo": float(np.exp(beta - 1.96 * se)),
        "ci_hi": float(np.exp(beta + 1.96 * se)),
        "p": float(cph.summary.loc[var, "p"]),
    }


def cindex_from_risk(df: pd.DataFrame, time_col: str, event_col: str, risk: np.ndarray) -> float:
    return float(
        concordance_index(
            df[time_col].to_numpy(dtype=float),
            -np.asarray(risk, dtype=float).reshape(-1),
            df[event_col].to_numpy(dtype=int),
        )
    )


def model_cindex(cph: CoxPHFitter, fit_df: pd.DataFrame, time_col: str, event_col: str) -> float:
    risk = cph.predict_log_partial_hazard(fit_df).to_numpy().reshape(-1)
    return cindex_from_risk(fit_df, time_col, event_col, risk)


def lrt_stats(cph_full: CoxPHFitter, cph_reduced: CoxPHFitter, df_diff: int = 1) -> Tuple[float, float]:
    stat = 2.0 * (float(cph_full.log_likelihood_) - float(cph_reduced.log_likelihood_))
    if not np.isfinite(stat) or stat < 0:
        return np.nan, np.nan
    return stat, float(chi2.sf(stat, df_diff))


def empty_result(args, horizon: str, status: str, error: str = "") -> Dict[str, object]:
    info = ENDPOINTS[args.endpoint]
    out = {
        "endpoint": args.endpoint,
        "endpoint_label": info["label"],
        "endpoint_date_field": info["date_field"],
        "clock_organ": "Endocrine",
        "clock_training_horizon": horizon,
        "clock_source_column": CLOCK_COLUMNS[horizon],
        "analysis_split": args.analysis_split,
        "status": status,
        "error": error,
    }
    numeric = [
        "N",
        "N_case",
        "N_noncase",
        "N_prevalent_excluded",
        "event_rate",
        "followup_years_min",
        "followup_years_median",
        "followup_years_max",
        "event_followup_years_min",
        "event_followup_years_median",
        "event_followup_years_max",
        "clock_raw_mean",
        "clock_raw_sd",
        "clock_beta",
        "clock_se",
        "clock_hr_per_1sd",
        "clock_ci_lo",
        "clock_ci_hi",
        "clock_p",
        "clock_only_cindex",
        "covariate_only_cindex",
        "full_model_cindex",
        "delta_cindex_full_minus_covariates",
        "lrt_chisq_clock_vs_covariates",
        "lrt_p_clock_vs_covariates",
        "penalizer_covariate_model",
        "penalizer_full_model",
    ]
    for c in numeric:
        out[c] = np.nan
    return out


def prepare_common_fit_pool(data_all: pd.DataFrame, args):
    data = data_all.copy()
    n_prev = int(data["prevalent_or_prior_to_baseline"].sum())
    data = data.loc[data["prevalent_or_prior_to_baseline"] != 1].copy()
    data = data.loc[data["time_from_baseline_to_disease_or_censor_days"] > 0].copy()

    covars = base_covariates(data, args.include_bp)
    time_col = "time_from_baseline_to_disease_or_censor_days"
    event_col = "disease_case"

    required = [time_col, event_col, "participant_id"] + covars + list(CLOCK_COLUMNS.values())
    fit_pool = data[required].copy()
    numeric_cols = [time_col, event_col] + covars + list(CLOCK_COLUMNS.values())
    for c in numeric_cols:
        fit_pool[c] = pd.to_numeric(fit_pool[c], errors="coerce")
    fit_pool = fit_pool.replace([np.inf, -np.inf], np.nan).dropna().copy()
    fit_pool = fit_pool.loc[fit_pool[time_col] > 0].copy()

    for horizon in HORIZON_ORDER:
        raw_col = CLOCK_COLUMNS[horizon]
        z_col = f"epoch_{horizon}_analysis_z"
        fit_pool[z_col], _, _ = standardize_on_common_pool(fit_pool[raw_col])

    return fit_pool, covars, time_col, event_col, n_prev


def analyze_horizon_models(data_all: pd.DataFrame, args):
    fit_pool, covars, time_col, event_col, n_prev = prepare_common_fit_pool(data_all, args)

    n_case = int(fit_pool[event_col].sum())
    n_noncase = int((fit_pool[event_col] == 0).sum())
    if n_case < args.min_case or n_noncase < args.min_noncase:
        rows = []
        for horizon in HORIZON_ORDER:
            row = empty_result(args, horizon, "insufficient_events")
            row.update(
                {
                    "N": int(len(fit_pool)),
                    "N_case": n_case,
                    "N_noncase": n_noncase,
                    "N_prevalent_excluded": n_prev,
                }
            )
            rows.append(row)
        return pd.DataFrame(rows), pd.DataFrame(), fit_pool, pd.DataFrame()

    # One identical covariate-only reference model for all three EPOCH clocks.
    cph_base, df_base, covars_used, pen_base = fit_cox(
        fit_pool,
        time_col=time_col,
        event_col=event_col,
        predictors=covars,
        penalizer=args.penalizer,
    )
    base_c = model_cindex(cph_base, df_base, time_col, event_col)

    rows = []
    risk_predictions_full = {}
    risk_predictions_clock_only = {}

    followup_years = fit_pool[time_col].astype(float) / 365.25
    event_followup_years = followup_years.loc[fit_pool[event_col] == 1]

    for horizon in HORIZON_ORDER:
        raw_col = CLOCK_COLUMNS[horizon]
        z_col = f"epoch_{horizon}_analysis_z"

        try:
            cph_full, df_full, predictors_used, pen_full = fit_cox(
                fit_pool,
                time_col=time_col,
                event_col=event_col,
                predictors=covars_used + [z_col],
                penalizer=args.penalizer,
            )
            stats = extract_hr(cph_full, z_col)
            full_c = model_cindex(cph_full, df_full, time_col, event_col)
            # A standard likelihood-ratio test is appropriate only for the
            # unpenalized nested Cox models. If numerical fallback required a
            # penalizer, leave the LRT missing rather than report a nonstandard test.
            if float(pen_base) == 0.0 and float(pen_full) == 0.0:
                lrt_chisq, lrt_p = lrt_stats(cph_full, cph_base, df_diff=1)
            else:
                lrt_chisq, lrt_p = np.nan, np.nan

            # Clock-only ranking, no refitting needed because monotonic rescaling does not alter C-index.
            clock_only_c = cindex_from_risk(
                fit_pool,
                time_col,
                event_col,
                fit_pool[z_col].to_numpy(),
            )
            risk_predictions_full[horizon] = cph_full.predict_log_partial_hazard(
                fit_pool[covars_used + [z_col]]
            ).to_numpy().reshape(-1)
            # The standardized EPOCH itself is a monotonic disease-risk score for
            # the clock-only comparison.
            risk_predictions_clock_only[horizon] = fit_pool[z_col].to_numpy(dtype=float)

            row = empty_result(args, horizon, "ok")
            row.update(
                {
                    "N": int(len(fit_pool)),
                    "N_case": n_case,
                    "N_noncase": n_noncase,
                    "N_prevalent_excluded": n_prev,
                    "event_rate": float(n_case / len(fit_pool)),
                    "followup_years_min": float(followup_years.min()),
                    "followup_years_median": float(followup_years.median()),
                    "followup_years_max": float(followup_years.max()),
                    "event_followup_years_min": float(event_followup_years.min()),
                    "event_followup_years_median": float(event_followup_years.median()),
                    "event_followup_years_max": float(event_followup_years.max()),
                    "clock_raw_mean": float(fit_pool[raw_col].mean()),
                    "clock_raw_sd": float(fit_pool[raw_col].std(ddof=1)),
                    "clock_beta": stats["beta"],
                    "clock_se": stats["se"],
                    "clock_hr_per_1sd": stats["hr"],
                    "clock_ci_lo": stats["ci_lo"],
                    "clock_ci_hi": stats["ci_hi"],
                    "clock_p": stats["p"],
                    "clock_only_cindex": clock_only_c,
                    "covariate_only_cindex": base_c,
                    "full_model_cindex": full_c,
                    "delta_cindex_full_minus_covariates": full_c - base_c,
                    "lrt_chisq_clock_vs_covariates": lrt_chisq,
                    "lrt_p_clock_vs_covariates": lrt_p,
                    "penalizer_covariate_model": pen_base,
                    "penalizer_full_model": pen_full,
                    "covariates_used": ",".join(covars_used),
                }
            )
        except Exception as exc:
            row = empty_result(args, horizon, "cox_fit_failed", str(exc))
            row.update(
                {
                    "N": int(len(fit_pool)),
                    "N_case": n_case,
                    "N_noncase": n_noncase,
                    "N_prevalent_excluded": n_prev,
                }
            )
        rows.append(row)

    res = pd.DataFrame(rows)

    pairwise = paired_bootstrap_cindex_comparisons(
        fit_pool,
        time_col,
        event_col,
        {
            "covariates_plus_epoch": risk_predictions_full,
            "epoch_only": risk_predictions_clock_only,
        },
        args.n_bootstrap,
        args.random_state,
        args,
    )
    corr = clock_correlations(fit_pool)
    return res, pairwise, fit_pool, corr


def paired_bootstrap_cindex_comparisons(
    fit_pool: pd.DataFrame,
    time_col: str,
    event_col: str,
    risk_prediction_sets: Dict[str, Dict[str, np.ndarray]],
    n_boot: int,
    random_state: int,
    args,
) -> pd.DataFrame:
    rows = []
    n = len(fit_pool)
    time = fit_pool[time_col].to_numpy(dtype=float)
    event = fit_pool[event_col].to_numpy(dtype=int)

    for prediction_type, risk_predictions in risk_prediction_sets.items():
        for pair_index, (a, b) in enumerate(combinations(HORIZON_ORDER, 2)):
            if a not in risk_predictions or b not in risk_predictions:
                continue
            ra = np.asarray(risk_predictions[a], dtype=float)
            rb = np.asarray(risk_predictions[b], dtype=float)
            c_a = float(concordance_index(time, -ra, event))
            c_b = float(concordance_index(time, -rb, event))
            delta = c_a - c_b

            type_offset = 0 if prediction_type == "covariates_plus_epoch" else 100000
            rng = np.random.default_rng(
                random_state + type_offset + 1000 * (pair_index + 1)
            )
            boots = []
            for _ in range(n_boot):
                idx = rng.integers(0, n, size=n)
                if np.sum(event[idx]) < 2 or np.sum(event[idx] == 0) < 2:
                    continue
                try:
                    ca = float(concordance_index(time[idx], -ra[idx], event[idx]))
                    cb = float(concordance_index(time[idx], -rb[idx], event[idx]))
                    d = ca - cb
                    if np.isfinite(d):
                        boots.append(d)
                except Exception:
                    continue

            boots = np.asarray(boots, dtype=float)
            if boots.size:
                lo, hi = np.quantile(boots, [0.025, 0.975])
                p_le0 = float(np.mean(boots <= 0.0))
                p_ge0 = float(np.mean(boots >= 0.0))
                p2 = float(min(1.0, 2.0 * min(p_le0, p_ge0)))
            else:
                lo = hi = p2 = p_le0 = np.nan

            rows.append(
                {
                    "endpoint": args.endpoint,
                    "endpoint_label": ENDPOINTS[args.endpoint]["label"],
                    "analysis_split": args.analysis_split,
                    "prediction_type": prediction_type,
                    "comparison": f"{a}_minus_{b}",
                    "model_a": a,
                    "model_b": b,
                    "cindex_a": c_a,
                    "cindex_b": c_b,
                    "delta_cindex_a_minus_b": delta,
                    "delta_cindex_ci_lower": float(lo) if np.isfinite(lo) else np.nan,
                    "delta_cindex_ci_upper": float(hi) if np.isfinite(hi) else np.nan,
                    "n_bootstrap_requested": int(n_boot),
                    "n_bootstrap_successful": int(boots.size),
                    "empirical_p_two_sided_delta_not_equal_0": p2,
                    "empirical_p_one_sided_delta_le_0": p_le0,
                    "bootstrap_note": (
                        "Participant bootstrap of C-index difference using fixed risk scores; "
                        "disease Cox models are not refit within each bootstrap."
                    ),
                }
            )
    return pd.DataFrame(rows)


def clock_correlations(fit_pool: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for a, b in combinations(HORIZON_ORDER, 2):
        ca = CLOCK_COLUMNS[a]
        cb = CLOCK_COLUMNS[b]
        x = pd.to_numeric(fit_pool[ca], errors="coerce")
        y = pd.to_numeric(fit_pool[cb], errors="coerce")
        ok = x.notna() & y.notna()
        rows.append(
            {
                "horizon_a": a,
                "horizon_b": b,
                "n_pair": int(ok.sum()),
                "pearson_r": float(x[ok].corr(y[ok], method="pearson")),
                "spearman_rho": float(x[ok].corr(y[ok], method="spearman")),
            }
        )
    return pd.DataFrame(rows)


def fmt_p(p: float) -> str:
    if p is None or not np.isfinite(p):
        return "NA"
    if p < 1e-300:
        return "<1e-300"
    if p < 0.001:
        return f"{p:.2e}"
    return f"{p:.3f}"


def make_forest_plot(res: pd.DataFrame, args):
    ok = res.loc[(res["status"] == "ok") & res["clock_hr_per_1sd"].notna()].copy()
    if ok.empty:
        return
    try:
        import matplotlib.pyplot as plt
    except Exception as exc:
        warnings.warn(f"matplotlib is not available; skipping plot: {exc}")
        return

    order_map = {h: i for i, h in enumerate(HORIZON_ORDER)}
    ok["order"] = ok["clock_training_horizon"].map(order_map)
    ok = ok.sort_values("order", ascending=False)

    y = np.arange(ok.shape[0])
    hr = ok["clock_hr_per_1sd"].astype(float).to_numpy()
    lo = ok["clock_ci_lo"].astype(float).to_numpy()
    hi = ok["clock_ci_hi"].astype(float).to_numpy()
    labels = ok["clock_training_horizon"].map(
        {"5y": "5-year EPOCH", "10y": "10-year EPOCH", "full": "Full-follow-up EPOCH"}
    ).to_numpy()

    fig, ax = plt.subplots(figsize=(9.2, 4.6))
    ax.axvline(1.0, linestyle="--", linewidth=1.0)
    ax.errorbar(hr, y, xerr=[hr - lo, hi - hr], fmt="o", capsize=3, linewidth=1.2)
    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.set_xscale("log")
    ax.set_xlabel("Hazard ratio per 1 SD higher baseline Endocrine EPOCH")
    ax.set_title(
        f"{ENDPOINTS[args.endpoint]['label']}: Endocrine mortality EPOCH by training horizon"
    )

    xmax = max(np.nanmax(hi), 1.05)
    xmin = min(np.nanmin(lo), 0.95)
    ax.set_xlim(max(0.2, xmin * 0.85), xmax * 1.8)
    text_x = xmax * 1.08
    for i, row in enumerate(ok.itertuples(index=False)):
        txt = (
            f"HR {row.clock_hr_per_1sd:.2f} ({row.clock_ci_lo:.2f}-{row.clock_ci_hi:.2f}); "
            f"P={fmt_p(row.clock_p)}; C={row.full_model_cindex:.3f}"
        )
        ax.text(text_x, i, txt, va="center", fontsize=8.5)

    ax.grid(axis="x", alpha=0.25)
    fig.tight_layout()
    prefix = os.path.splitext(args.output_tsv)[0]
    for ext in ["png", "pdf", "svg"]:
        fig.savefig(f"{prefix}_horizon_clock_forest_plot.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)


def main():
    args = parse_args()
    output_dir = os.path.dirname(os.path.abspath(args.output_tsv))
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 72)
    print("Endocrine metabolomics EPOCH mortality-horizon -> disease onset")
    print(f"Endpoint: {args.endpoint} ({ENDPOINTS[args.endpoint]['label']})")
    print(f"Analysis split: {args.analysis_split}")
    print(f"Horizon prediction file: {args.horizon_predictions}")
    print(f"Bootstrap replicates: {args.n_bootstrap}")
    print("=" * 72)

    data = prepare_survival_dataset(args)
    res, pairwise, fit_pool, corr = analyze_horizon_models(data, args)

    res.to_csv(args.output_tsv, sep="\t", index=False)
    prefix = os.path.splitext(args.output_tsv)[0]
    pairwise_tsv = prefix + "_paired_delta_cindex.tsv"
    corr_tsv = prefix + "_clock_correlations.tsv"
    pairwise.to_csv(pairwise_tsv, sep="\t", index=False)
    corr.to_csv(corr_tsv, sep="\t", index=False)

    analysis_dataset_tsv = prefix + "_analysis_dataset.tsv"
    if not args.no_save_analysis_dataset:
        data.to_csv(analysis_dataset_tsv, sep="\t", index=False)

    complete_case_tsv = prefix + "_common_complete_cases.tsv"
    fit_pool.to_csv(complete_case_tsv, sep="\t", index=False)

    summary = {
        "endpoint": args.endpoint,
        "endpoint_info": ENDPOINTS[args.endpoint],
        "analysis_split": args.analysis_split,
        "horizon_predictions": args.horizon_predictions,
        "clock_columns": CLOCK_COLUMNS,
        "output_tsv": args.output_tsv,
        "pairwise_cindex_tsv": pairwise_tsv,
        "clock_correlations_tsv": corr_tsv,
        "analysis_dataset_tsv": None if args.no_save_analysis_dataset else analysis_dataset_tsv,
        "common_complete_cases_tsv": complete_case_tsv,
        "n_input_clock_rows": int(data.shape[0]),
        "n_prevalent_or_prior_to_baseline": int(data["prevalent_or_prior_to_baseline"].sum()),
        "n_incident_events_after_baseline": int(data["disease_case"].sum()),
        "n_common_complete_cases": int(fit_pool.shape[0]),
        "n_common_complete_case_events": int(fit_pool["disease_case"].sum()) if not fit_pool.empty else 0,
        "primary_predictor": "baseline Endocrine EPOCH acceleration, re-standardized to 1 SD within the disease-specific common complete-case cohort",
        "time_zero": "UKB baseline assessment/sample date carried in the horizon-clock prediction file",
        "censoring": "earlier of all-cause death and administrative censor date",
        "comparison_principle": "same disease cohort, same covariates, only mortality-clock training horizon differs",
    }
    with open(prefix + "_run_summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=str)

    if not args.no_plot:
        make_forest_plot(res, args)

    print("\nPrimary horizon-specific results:")
    cols = [
        "clock_training_horizon",
        "N",
        "N_case",
        "clock_hr_per_1sd",
        "clock_ci_lo",
        "clock_ci_hi",
        "clock_p",
        "covariate_only_cindex",
        "full_model_cindex",
        "delta_cindex_full_minus_covariates",
        "lrt_p_clock_vs_covariates",
    ]
    print(res[cols].to_string(index=False))
    print("\nPairwise C-index comparisons:")
    if pairwise.empty:
        print("  none")
    else:
        print(pairwise.to_string(index=False))
    print("\nClock correlations in common disease cohort:")
    print(corr.to_string(index=False))
    print("\nFinished.")
    print(f"Primary results: {args.output_tsv}")
    print(f"Paired C-index comparisons: {pairwise_tsv}")
    print(f"Clock correlations: {corr_tsv}")
    print(f"Common complete cases: {complete_case_tsv}")


if __name__ == "__main__":
    main()
