#!/usr/bin/env python3
"""
Cumulative survival analysis of CN-to-MCI/AD conversion in ADNI.

The analysis starts from the participant-level prediction file generated by the
original AD EPOCH development script. That file contains one baseline-CN row per
participant, the CN-to-MCI/AD survival outcome, split labels, and the frozen
AD EPOCH score. All available development participants (train, validation, and
test) are retained because this analysis evaluates incremental association and
prediction within the full ADNI development cohort rather than external model
validation.

Cumulative model order
----------------------
M0: Age + Sex
M1: M0 + Abeta_CSF
M2: M1 + Tau_CSF + PTau_CSF
M3: M2 + SPARE_BA
M4: M3 + SPARE_AD
M5: M4 + AD EPOCH risk score

Biomarker alignment
-------------------
* Age, Sex, SPARE_BA, and SPARE_AD are taken from the exact selected baseline-CN
  MRI row when possible, using PTID + selected baseline visit, with date-based
  fallback.
* For each CSF marker, the subject's first chronologically available nonmissing
  measurement is used, as requested. Its date relative to the baseline MRI is
  retained in QC output so post-baseline measurements can be identified.
* The primary cumulative comparison uses one common complete-case cohort across
  all six models, ensuring each incremental C-index comparison uses identical
  participants.

Outputs
-------
* baseline analysis dataset
* baseline matching and first-CSF QC tables
* missingness and complete-case summaries
* model performance with apparent and five-fold out-of-fold C-index
* cumulative incremental comparisons with paired bootstrap delta C-index and
  likelihood-ratio tests
* full-model coefficients / hazard ratios
* participant-level out-of-fold risk predictions
* JSON analysis summary

Required packages
-----------------
pandas, numpy, scipy, scikit-learn, lifelines
"""

from __future__ import annotations

import argparse
import json
import re
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import numpy as np
import pandas as pd
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index
from scipy.stats import chi2
from sklearn.model_selection import StratifiedKFold


DEFAULT_EPOCH_COL = "adni_brain_mri_ad_lepoch_risk_score"
DEFAULT_AMYLOID_COL = "Abeta_CSF"
DEFAULT_TAU_COLS = ("Tau_CSF", "PTau_CSF")
DEFAULT_SPARE_BA_COL = "SPARE_BA"
DEFAULT_SPARE_AD_COL = "SPARE_AD"


@dataclass(frozen=True)
class ModelSpec:
    step: int
    name: str
    added_block: str
    predictors: tuple[str, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run cumulative CN-to-MCI/AD Cox analyses adding amyloid, tau, "
            "SPARE-BA, SPARE-AD, and AD EPOCH to Age + Sex."
        )
    )

    parser.add_argument("--epoch-predictions-file", required=True)
    parser.add_argument("--adni-file", required=True)
    parser.add_argument("--outdir", required=True)
    parser.add_argument(
        "--prefix",
        default="adni_cn_mciad_cumulative_biomarkers",
    )

    parser.add_argument("--id-col", default="PTID")
    parser.add_argument("--visit-col", default="Visit_Code")
    parser.add_argument("--date-col", default="Date")
    parser.add_argument(
        "--baseline-visit-col",
        default="selected_baseline_visit_code",
    )
    parser.add_argument(
        "--baseline-date-col",
        default="selected_baseline_date",
    )
    parser.add_argument("--time-col", default="time_years")
    parser.add_argument("--event-col", default="event")
    parser.add_argument("--epoch-col", default=DEFAULT_EPOCH_COL)

    parser.add_argument("--age-col", default="Age")
    parser.add_argument("--sex-col", default="Sex")
    parser.add_argument("--amyloid-col", default=DEFAULT_AMYLOID_COL)
    parser.add_argument("--tau-cols", default=",".join(DEFAULT_TAU_COLS))
    parser.add_argument("--spare-ba-col", default=DEFAULT_SPARE_BA_COL)
    parser.add_argument("--spare-ad-col", default=DEFAULT_SPARE_AD_COL)

    parser.add_argument("--cv-folds", type=int, default=5)
    parser.add_argument("--random-state", type=int, default=20260730)
    parser.add_argument("--cox-penalizer", type=float, default=0.01)
    parser.add_argument("--bootstrap", type=int, default=1000)
    parser.add_argument("--minimum-n", type=int, default=50)
    parser.add_argument("--minimum-events", type=int, default=20)
    parser.add_argument(
        "--allow-stage-specific-samples",
        action="store_true",
        help=(
            "Also run secondary stage-specific complete-case analyses. "
            "The primary cumulative analysis always uses the common complete-case cohort."
        ),
    )

    return parser.parse_args()


def log(message: str) -> None:
    print(message, flush=True)


def parse_list(value: str | None) -> list[str]:
    if value is None or not str(value).strip():
        return []
    return [x.strip() for x in str(value).split(",") if x.strip()]


def read_table(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if not path.exists() or path.stat().st_size == 0:
        raise FileNotFoundError(f"Missing or empty input file: {path}")
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path, low_memory=False)
    return pd.read_csv(path, sep="\t", low_memory=False)


def clean_id(series: pd.Series) -> pd.Series:
    out = series.astype("object").where(series.notna(), np.nan)
    return out.astype(str).str.strip()


def clean_numeric(series: pd.Series) -> pd.Series:
    if pd.api.types.is_numeric_dtype(series):
        return pd.to_numeric(series, errors="coerce")

    cleaned = (
        series.astype("object")
        .where(series.notna(), np.nan)
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
        .replace(
            {
                "": np.nan,
                "nan": np.nan,
                "NaN": np.nan,
                "NA": np.nan,
                "N/A": np.nan,
                "None": np.nan,
                "null": np.nan,
            }
        )
    )

    extracted = cleaned.astype(str).str.extract(
        r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
        expand=False,
    )
    extracted = extracted.where(cleaned.notna(), np.nan)
    return pd.to_numeric(extracted, errors="coerce")


def normalize_sex(series: pd.Series) -> pd.Series:
    return (
        series.astype("object")
        .where(series.notna(), np.nan)
        .astype(str)
        .str.strip()
        .replace(
            {
                "0": "Female",
                "0.0": "Female",
                "1": "Male",
                "1.0": "Male",
                "F": "Female",
                "M": "Male",
                "female": "Female",
                "male": "Male",
                "FEMALE": "Female",
                "MALE": "Male",
            }
        )
    )


def parse_bool_event(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.astype(int)

    numeric = pd.to_numeric(series, errors="coerce")
    text = series.astype(str).str.strip().str.lower()
    mapping = {
        "true": 1,
        "t": 1,
        "yes": 1,
        "y": 1,
        "event": 1,
        "false": 0,
        "f": 0,
        "no": 0,
        "n": 0,
        "censored": 0,
    }
    numeric.loc[numeric.isna()] = text.loc[numeric.isna()].map(mapping)
    return numeric.astype("Int64")


def visit_code_to_month(value: object) -> float:
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    if text in {"bl", "base", "baseline", "m00", "m0", "screen", "screening", "sc"}:
        return 0.0
    match = re.search(r"m(?:onth)?\s*0*([0-9]+)", text)
    if match:
        return float(match.group(1))
    match = re.search(r"([0-9]+)", text)
    return float(match.group(1)) if match else np.nan


def make_sort_key(df: pd.DataFrame, date_col: str, visit_col: str) -> pd.Series:
    dates = pd.to_datetime(df[date_col], errors="coerce")
    date_key = dates.map(lambda x: x.toordinal() if pd.notna(x) else np.nan)
    visit_key = df[visit_col].map(visit_code_to_month) * 30.4375
    return date_key.fillna(visit_key)


def select_baseline_rows(
    predictions: pd.DataFrame,
    adni: pd.DataFrame,
    args: argparse.Namespace,
    requested_cols: Sequence[str],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Match the selected baseline-CN MRI row for every prediction record."""

    s = predictions[
        [args.id_col, args.baseline_visit_col, args.baseline_date_col]
    ].copy()
    s[args.id_col] = clean_id(s[args.id_col])
    s["_baseline_visit"] = (
        s[args.baseline_visit_col].astype(str).str.strip().str.lower()
    )
    s["_baseline_date"] = pd.to_datetime(
        s[args.baseline_date_col], errors="coerce"
    )

    a = adni.copy()
    a[args.id_col] = clean_id(a[args.id_col])
    a["_row_visit"] = a[args.visit_col].astype(str).str.strip().str.lower()
    a["_row_date"] = pd.to_datetime(a[args.date_col], errors="coerce")

    missing_cols = sorted(set(requested_cols) - set(a.columns))
    if missing_cols:
        warnings.warn(f"Requested baseline fields absent from ADNI: {missing_cols}")

    grouped = {
        pid: group.copy()
        for pid, group in a.groupby(args.id_col, sort=False)
    }

    rows: list[dict] = []
    qc_rows: list[dict] = []

    # iterrows is intentional: itertuples renames underscore-prefixed columns.
    for _, record in s.iterrows():
        pid = str(record[args.id_col]).strip()
        baseline_visit = str(record["_baseline_visit"]).strip().lower()
        baseline_date = record["_baseline_date"]
        group = grouped.get(pid)

        selected = None
        method = "unmatched"
        difference_days = np.nan

        if group is not None and not group.empty:
            by_visit = group.loc[group["_row_visit"] == baseline_visit].copy()

            if not by_visit.empty:
                if pd.notna(baseline_date) and by_visit["_row_date"].notna().any():
                    differences = (by_visit["_row_date"] - baseline_date).abs().dt.days
                    selected_index = differences.idxmin()
                    selected = by_visit.loc[selected_index]
                    difference_days = float(differences.loc[selected_index])
                else:
                    selected = by_visit.iloc[0]
                method = "PTID+Visit_Code"

            elif pd.notna(baseline_date) and group["_row_date"].notna().any():
                differences = (group["_row_date"] - baseline_date).abs().dt.days
                selected_index = differences.idxmin()
                minimum = float(differences.loc[selected_index])
                if minimum == 0.0:
                    selected = group.loc[selected_index]
                    difference_days = 0.0
                    method = "PTID+exact_Date"

        output = {args.id_col: pid}
        for col in requested_cols:
            output[col] = (
                selected[col]
                if selected is not None and col in selected.index
                else np.nan
            )
        rows.append(output)

        qc_rows.append(
            {
                args.id_col: pid,
                "selected_baseline_visit_code": record[args.baseline_visit_col],
                "selected_baseline_date": baseline_date,
                "baseline_match_method": method,
                "baseline_match_date_difference_days": difference_days,
                "baseline_row_found": selected is not None,
            }
        )

    return pd.DataFrame(rows), pd.DataFrame(qc_rows)


def select_first_available_markers(
    adni: pd.DataFrame,
    args: argparse.Namespace,
    marker_cols: Sequence[str],
    baseline_dates: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Select each participant's first available nonmissing value per CSF marker."""

    a = adni.copy()
    a[args.id_col] = clean_id(a[args.id_col])
    a["_row_date"] = pd.to_datetime(a[args.date_col], errors="coerce")
    a["_sort_key"] = make_sort_key(a, args.date_col, args.visit_col)

    available = [col for col in marker_cols if col in a.columns]
    missing = sorted(set(marker_cols) - set(available))
    if missing:
        warnings.warn(f"Requested CSF markers absent from ADNI: {missing}")

    baseline_lookup = baseline_dates.copy()
    baseline_lookup[args.id_col] = clean_id(baseline_lookup[args.id_col])
    baseline_lookup["_baseline_date"] = pd.to_datetime(
        baseline_lookup[args.baseline_date_col], errors="coerce"
    )
    baseline_lookup = baseline_lookup.set_index(args.id_col)["_baseline_date"].to_dict()

    grouped = {
        pid: group.sort_values("_sort_key", kind="mergesort").copy()
        for pid, group in a.groupby(args.id_col, sort=False)
    }

    participants = baseline_dates[args.id_col].map(str).str.strip().tolist()
    value_rows: list[dict] = []
    qc_rows: list[dict] = []

    for pid in participants:
        group = grouped.get(pid)
        baseline_date = baseline_lookup.get(pid, pd.NaT)
        value_record = {args.id_col: pid}
        qc_record = {args.id_col: pid}

        for marker in marker_cols:
            selected = None
            if group is not None and marker in group.columns:
                numeric = clean_numeric(group[marker])
                candidates = group.loc[numeric.notna()].copy()
                if not candidates.empty:
                    candidates["_marker_numeric"] = numeric.loc[candidates.index]
                    candidates = candidates.sort_values("_sort_key", kind="mergesort")
                    selected = candidates.iloc[0]

            if selected is None:
                value_record[marker] = np.nan
                qc_record[f"{marker}_first_value"] = np.nan
                qc_record[f"{marker}_first_visit_code"] = np.nan
                qc_record[f"{marker}_first_date"] = pd.NaT
                qc_record[f"{marker}_days_from_baseline"] = np.nan
                qc_record[f"{marker}_timing"] = "missing"
            else:
                marker_date = selected["_row_date"]
                value = float(selected["_marker_numeric"])
                if pd.notna(marker_date) and pd.notna(baseline_date):
                    days = float((marker_date - baseline_date).days)
                    if days < 0:
                        timing = "prebaseline"
                    elif days == 0:
                        timing = "same_day"
                    else:
                        timing = "postbaseline"
                else:
                    days = np.nan
                    timing = "date_unavailable"

                value_record[marker] = value
                qc_record[f"{marker}_first_value"] = value
                qc_record[f"{marker}_first_visit_code"] = selected[args.visit_col]
                qc_record[f"{marker}_first_date"] = marker_date
                qc_record[f"{marker}_days_from_baseline"] = days
                qc_record[f"{marker}_timing"] = timing

        value_rows.append(value_record)
        qc_rows.append(qc_record)

    return pd.DataFrame(value_rows), pd.DataFrame(qc_rows)


def prepare_analysis_dataset(
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    predictions = read_table(args.epoch_predictions_file)
    adni = read_table(args.adni_file)

    required_predictions = [
        args.id_col,
        args.baseline_visit_col,
        args.baseline_date_col,
        args.time_col,
        args.event_col,
        args.epoch_col,
    ]
    missing = [col for col in required_predictions if col not in predictions.columns]
    if missing:
        raise ValueError(f"AD EPOCH prediction file is missing columns: {missing}")

    required_adni = [args.id_col, args.visit_col, args.date_col]
    missing = [col for col in required_adni if col not in adni.columns]
    if missing:
        raise ValueError(f"ADNI file is missing columns: {missing}")

    predictions = predictions.copy()
    predictions[args.id_col] = clean_id(predictions[args.id_col])
    if predictions[args.id_col].duplicated().any():
        duplicates = predictions.loc[
            predictions[args.id_col].duplicated(), args.id_col
        ].head(10).tolist()
        raise ValueError(
            "Prediction file must contain one baseline row per participant. "
            f"Duplicate IDs include: {duplicates}"
        )

    tau_cols = parse_list(args.tau_cols)
    baseline_fields = [
        args.age_col,
        args.sex_col,
        args.spare_ba_col,
        args.spare_ad_col,
    ]
    csf_fields = [args.amyloid_col] + tau_cols

    baseline_values, baseline_qc = select_baseline_rows(
        predictions,
        adni,
        args,
        baseline_fields,
    )

    first_csf, first_csf_qc = select_first_available_markers(
        adni,
        args,
        csf_fields,
        predictions[[args.id_col, args.baseline_date_col]],
    )

    # Prediction file is authoritative for outcome and AD EPOCH. Baseline fields
    # are re-sourced from the exact baseline ADNI row.
    base = predictions.drop(
        columns=[col for col in baseline_fields + csf_fields if col in predictions.columns],
        errors="ignore",
    )
    merged = base.merge(
        baseline_values,
        on=args.id_col,
        how="left",
        validate="one_to_one",
    )
    merged = merged.merge(
        first_csf,
        on=args.id_col,
        how="left",
        validate="one_to_one",
    )

    merged[args.time_col] = clean_numeric(merged[args.time_col])
    merged[args.event_col] = parse_bool_event(merged[args.event_col])
    merged[args.epoch_col] = clean_numeric(merged[args.epoch_col])
    merged[args.age_col] = clean_numeric(merged[args.age_col])
    merged[args.sex_col] = normalize_sex(merged[args.sex_col])

    for col in csf_fields + [args.spare_ba_col, args.spare_ad_col]:
        if col in merged.columns:
            merged[col] = clean_numeric(merged[col])

    valid = (
        merged[args.id_col].notna()
        & merged[args.time_col].notna()
        & (merged[args.time_col] > 0)
        & merged[args.event_col].notna()
        & merged[args.epoch_col].notna()
    )
    if (~valid).any():
        warnings.warn(
            f"Removed {int((~valid).sum())} rows with invalid ID, time, event, or AD EPOCH score."
        )
    merged = merged.loc[valid].copy()
    merged[args.event_col] = merged[args.event_col].astype(int)

    qc = baseline_qc.merge(
        first_csf_qc,
        on=args.id_col,
        how="left",
        validate="one_to_one",
    )

    return merged, qc, predictions


def make_model_specs(args: argparse.Namespace) -> list[ModelSpec]:
    tau_cols = tuple(parse_list(args.tau_cols))
    baseline = (args.age_col, args.sex_col)

    return [
        ModelSpec(0, "M0_age_sex", "Age + Sex", baseline),
        ModelSpec(
            1,
            "M1_plus_amyloid",
            args.amyloid_col,
            baseline + (args.amyloid_col,),
        ),
        ModelSpec(
            2,
            "M2_plus_tau",
            "+".join(tau_cols),
            baseline + (args.amyloid_col,) + tau_cols,
        ),
        ModelSpec(
            3,
            "M3_plus_SPARE_BA",
            args.spare_ba_col,
            baseline
            + (args.amyloid_col,)
            + tau_cols
            + (args.spare_ba_col,),
        ),
        ModelSpec(
            4,
            "M4_plus_SPARE_AD",
            args.spare_ad_col,
            baseline
            + (args.amyloid_col,)
            + tau_cols
            + (args.spare_ba_col, args.spare_ad_col),
        ),
        ModelSpec(
            5,
            "M5_plus_AD_EPOCH",
            args.epoch_col,
            baseline
            + (args.amyloid_col,)
            + tau_cols
            + (args.spare_ba_col, args.spare_ad_col, args.epoch_col),
        ),
    ]


def predictor_types(
    predictors: Sequence[str],
    args: argparse.Namespace,
) -> tuple[list[str], list[str]]:
    categorical = [col for col in predictors if col == args.sex_col]
    numeric = [col for col in predictors if col not in categorical]
    return numeric, categorical


def fit_preprocessor(
    train: pd.DataFrame,
    test: pd.DataFrame,
    predictors: Sequence[str],
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    numeric, categorical = predictor_types(predictors, args)
    train_out = pd.DataFrame(index=train.index)
    test_out = pd.DataFrame(index=test.index)
    metadata: dict = {"numeric": {}, "categorical": {}}

    for col in numeric:
        train_values = clean_numeric(train[col])
        test_values = clean_numeric(test[col])

        median = float(train_values.median()) if train_values.notna().any() else 0.0
        train_values = train_values.fillna(median)
        test_values = test_values.fillna(median)

        mean = float(train_values.mean())
        sd = float(train_values.std(ddof=0))
        if not np.isfinite(sd) or sd <= 0:
            sd = 1.0

        train_out[col] = (train_values - mean) / sd
        test_out[col] = (test_values - mean) / sd
        metadata["numeric"][col] = {"median": median, "mean": mean, "sd": sd}

    for col in categorical:
        train_values = train[col].astype("object")
        test_values = test[col].astype("object")

        mode = train_values.dropna().mode()
        fill = str(mode.iloc[0]) if not mode.empty else "Missing"
        train_values = train_values.where(train_values.notna(), fill).astype(str)
        test_values = test_values.where(test_values.notna(), fill).astype(str)

        levels = sorted(train_values.unique().tolist())
        reference = levels[0] if levels else fill
        metadata["categorical"][col] = {
            "fill": fill,
            "levels": levels,
            "reference": reference,
        }

        for level in levels[1:]:
            safe = re.sub(r"[^A-Za-z0-9]+", "_", level).strip("_") or "level"
            name = f"{col}__{safe}"
            train_out[name] = (train_values == level).astype(float)
            test_out[name] = (test_values == level).astype(float)

    keep = [
        col
        for col in train_out.columns
        if train_out[col].nunique(dropna=False) > 1
    ]
    if not keep:
        raise ValueError("No nonconstant transformed predictors remain.")

    return (
        train_out[keep],
        test_out.reindex(columns=keep, fill_value=0.0),
        metadata,
    )


def fit_cox_model(
    train: pd.DataFrame,
    test: pd.DataFrame,
    spec: ModelSpec,
    args: argparse.Namespace,
) -> tuple[CoxPHFitter, pd.DataFrame, pd.DataFrame, dict]:
    x_train, x_test, metadata = fit_preprocessor(
        train,
        test,
        spec.predictors,
        args,
    )

    fit_data = x_train.copy()
    fit_data[args.time_col] = train[args.time_col].astype(float).values
    fit_data[args.event_col] = train[args.event_col].astype(int).values

    last_error: Exception | None = None
    candidates = []
    for value in [args.cox_penalizer, 0.05, 0.1, 0.5, 1.0]:
        value = max(float(value), 0.0)
        if value not in candidates:
            candidates.append(value)

    for penalizer in candidates:
        try:
            model = CoxPHFitter(penalizer=penalizer)
            model.fit(
                fit_data,
                duration_col=args.time_col,
                event_col=args.event_col,
                show_progress=False,
            )
            metadata["penalizer_used"] = penalizer
            return model, x_train, x_test, metadata
        except Exception as exc:
            last_error = exc

    raise RuntimeError(f"Cox fitting failed after penalizer fallbacks: {last_error}")


def harrell_cindex(
    time: np.ndarray,
    event: np.ndarray,
    risk: np.ndarray,
) -> float:
    return float(concordance_index(time, -np.asarray(risk), event))


def make_cv_splits(data: pd.DataFrame, args: argparse.Namespace) -> list[tuple[np.ndarray, np.ndarray]]:
    counts = data[args.event_col].value_counts()
    if len(counts) < 2:
        raise ValueError("Both events and censored observations are required.")

    folds = min(args.cv_folds, int(counts.min()))
    if folds < 2:
        raise ValueError("Insufficient event/censor counts for cross-validation.")

    splitter = StratifiedKFold(
        n_splits=folds,
        shuffle=True,
        random_state=args.random_state,
    )
    return list(
        splitter.split(
            np.zeros(data.shape[0]),
            data[args.event_col].to_numpy(int),
        )
    )


def cross_validated_predictions(
    data: pd.DataFrame,
    spec: ModelSpec,
    splits: Sequence[tuple[np.ndarray, np.ndarray]],
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, float]:
    predictions = np.repeat(np.nan, data.shape[0])
    fold_ids = np.repeat(-1, data.shape[0])

    for fold, (train_index, test_index) in enumerate(splits, start=1):
        train = data.iloc[train_index].copy()
        test = data.iloc[test_index].copy()
        model, _, x_test, _ = fit_cox_model(train, test, spec, args)
        predictions[test_index] = model.predict_partial_hazard(x_test).to_numpy().reshape(-1)
        fold_ids[test_index] = fold

    if np.isnan(predictions).any():
        raise RuntimeError(f"OOF predictions incomplete for {spec.name}")

    cindex = harrell_cindex(
        data[args.time_col].to_numpy(float),
        data[args.event_col].to_numpy(int),
        predictions,
    )

    output = data[[args.id_col, args.time_col, args.event_col]].copy()
    output["model_step"] = spec.step
    output["analysis_model"] = spec.name
    output["added_block"] = spec.added_block
    output["fold"] = fold_ids
    output["oof_risk"] = predictions
    return output, cindex


def fit_full_model(
    data: pd.DataFrame,
    spec: ModelSpec,
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, float, int, float, float]:
    model, x, _, metadata = fit_cox_model(data, data, spec, args)

    summary = model.summary.reset_index().rename(
        columns={"covariate": "term", "index": "term"}
    )
    summary = summary.rename(
        columns={
            "coef": "log_hazard_coefficient",
            "exp(coef)": "hazard_ratio",
            "exp(coef) lower 95%": "hazard_ratio_ci_lower",
            "exp(coef) upper 95%": "hazard_ratio_ci_upper",
            "se(coef)": "standard_error",
            "p": "p_value",
        }
    )
    summary["model_step"] = spec.step
    summary["analysis_model"] = spec.name
    summary["added_block"] = spec.added_block
    summary["n"] = data.shape[0]
    summary["n_events"] = int(data[args.event_col].sum())
    summary["penalizer"] = metadata["penalizer_used"]

    wanted = [
        "model_step",
        "analysis_model",
        "added_block",
        "term",
        "log_hazard_coefficient",
        "hazard_ratio",
        "hazard_ratio_ci_lower",
        "hazard_ratio_ci_upper",
        "standard_error",
        "p_value",
        "n",
        "n_events",
        "penalizer",
    ]
    summary = summary[[col for col in wanted if col in summary.columns]]

    risk = model.predict_partial_hazard(x).to_numpy().reshape(-1)
    apparent_cindex = harrell_cindex(
        data[args.time_col].to_numpy(float),
        data[args.event_col].to_numpy(int),
        risk,
    )

    return (
        summary,
        float(model.log_likelihood_),
        int(x.shape[1]),
        apparent_cindex,
        float(metadata["penalizer_used"]),
    )


def paired_bootstrap_delta(
    data: pd.DataFrame,
    risk_new: np.ndarray,
    risk_previous: np.ndarray,
    args: argparse.Namespace,
    seed_offset: int,
) -> dict:
    rng = np.random.default_rng(args.random_state + seed_offset)
    time = data[args.time_col].to_numpy(float)
    event = data[args.event_col].to_numpy(int)
    risk_new = np.asarray(risk_new, dtype=float)
    risk_previous = np.asarray(risk_previous, dtype=float)

    c_new = harrell_cindex(time, event, risk_new)
    c_previous = harrell_cindex(time, event, risk_previous)
    observed_delta = c_new - c_previous

    boot: list[float] = []
    n = data.shape[0]
    for _ in range(args.bootstrap):
        indices = rng.integers(0, n, size=n)
        if np.unique(event[indices]).size < 2:
            continue
        try:
            delta = harrell_cindex(
                time[indices], event[indices], risk_new[indices]
            ) - harrell_cindex(
                time[indices], event[indices], risk_previous[indices]
            )
            if np.isfinite(delta):
                boot.append(delta)
        except Exception:
            continue

    array = np.asarray(boot, dtype=float)
    if array.size:
        lower, upper = np.quantile(array, [0.025, 0.975])
        p_le_zero = float(np.mean(array <= 0.0))
        p_ge_zero = float(np.mean(array >= 0.0))
        p_two = float(min(1.0, 2.0 * min(p_le_zero, p_ge_zero)))
    else:
        lower = upper = p_two = np.nan

    return {
        "cv_cindex_new": c_new,
        "cv_cindex_previous": c_previous,
        "delta_cv_cindex": observed_delta,
        "delta_cv_cindex_ci_lower": lower,
        "delta_cv_cindex_ci_upper": upper,
        "bootstrap_p_two_sided": p_two,
        "n_bootstrap_successful": int(array.size),
    }


def validate_common_cohort(
    data: pd.DataFrame,
    specs: Sequence[ModelSpec],
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, list[str]]:
    all_predictors = list(dict.fromkeys(specs[-1].predictors))
    required = all_predictors + [args.time_col, args.event_col]
    missing_columns = [col for col in required if col not in data.columns]
    if missing_columns:
        raise ValueError(f"Required analysis columns are absent: {missing_columns}")

    common = data.dropna(subset=required).copy()
    events = int(common[args.event_col].sum())
    censored = int(common.shape[0] - events)

    if (
        common.shape[0] < args.minimum_n
        or events < args.minimum_events
        or censored < args.minimum_events
    ):
        raise ValueError(
            "Common complete-case cohort is too small: "
            f"N={common.shape[0]}, events={events}, censored={censored}. "
            "Check first-available CSF extraction and biomarker coverage."
        )

    return common, all_predictors


def run_common_cumulative_analysis(
    common: pd.DataFrame,
    specs: Sequence[ModelSpec],
    args: argparse.Namespace,
) -> dict[str, pd.DataFrame]:
    splits = make_cv_splits(common, args)

    performance_rows: list[dict] = []
    coefficient_tables: list[pd.DataFrame] = []
    prediction_tables: list[pd.DataFrame] = []
    comparison_rows: list[dict] = []
    results: dict[str, dict] = {}

    for spec in specs:
        log(f"Fitting {spec.name}: {', '.join(spec.predictors)}")
        oof, cv_cindex = cross_validated_predictions(common, spec, splits, args)
        coefficients, log_likelihood, n_parameters, apparent_cindex, penalizer = fit_full_model(
            common,
            spec,
            args,
        )

        prediction_tables.append(oof)
        coefficient_tables.append(coefficients)
        performance_rows.append(
            {
                "analysis_sample": "common_complete_case",
                "model_step": spec.step,
                "model": spec.name,
                "added_block": spec.added_block,
                "predictors": ",".join(spec.predictors),
                "n": common.shape[0],
                "n_events": int(common[args.event_col].sum()),
                "n_censored": int(common.shape[0] - common[args.event_col].sum()),
                "cv_folds": len(splits),
                "cv_cindex": cv_cindex,
                "apparent_cindex": apparent_cindex,
                "log_likelihood": log_likelihood,
                "n_parameters": n_parameters,
                "penalizer": penalizer,
                "status": "success",
            }
        )

        results[spec.name] = {
            "spec": spec,
            "oof": oof,
            "log_likelihood": log_likelihood,
            "n_parameters": n_parameters,
        }

    for index in range(1, len(specs)):
        current = specs[index]
        previous = specs[index - 1]
        current_result = results[current.name]
        previous_result = results[previous.name]

        delta = paired_bootstrap_delta(
            common,
            current_result["oof"]["oof_risk"].to_numpy(float),
            previous_result["oof"]["oof_risk"].to_numpy(float),
            args,
            seed_offset=index,
        )

        lr_stat = 2.0 * (
            current_result["log_likelihood"]
            - previous_result["log_likelihood"]
        )
        lr_df = (
            current_result["n_parameters"]
            - previous_result["n_parameters"]
        )
        lr_p = (
            float(chi2.sf(max(lr_stat, 0.0), lr_df))
            if lr_df > 0
            else np.nan
        )

        comparison_rows.append(
            {
                "analysis_sample": "common_complete_case",
                "step": current.step,
                "added_block": current.added_block,
                "new_model": current.name,
                "previous_model": previous.name,
                "n": common.shape[0],
                "n_events": int(common[args.event_col].sum()),
                **delta,
                "likelihood_ratio_chi2": lr_stat,
                "likelihood_ratio_df": lr_df,
                "likelihood_ratio_p": lr_p,
            }
        )

    return {
        "performance": pd.DataFrame(performance_rows),
        "coefficients": pd.concat(coefficient_tables, ignore_index=True),
        "oof_predictions": pd.concat(prediction_tables, ignore_index=True),
        "cumulative_comparisons": pd.DataFrame(comparison_rows),
    }


def run_stage_specific_secondary(
    data: pd.DataFrame,
    specs: Sequence[ModelSpec],
    args: argparse.Namespace,
) -> pd.DataFrame:
    """Optional descriptive C-index analysis using each step's maximum sample."""
    rows: list[dict] = []

    for spec in specs:
        required = list(spec.predictors) + [args.time_col, args.event_col]
        if any(col not in data.columns for col in required):
            continue
        subset = data.dropna(subset=required).copy()
        events = int(subset[args.event_col].sum())
        censored = int(subset.shape[0] - events)

        if (
            subset.shape[0] < args.minimum_n
            or events < args.minimum_events
            or censored < args.minimum_events
        ):
            rows.append(
                {
                    "model_step": spec.step,
                    "model": spec.name,
                    "n": subset.shape[0],
                    "n_events": events,
                    "n_censored": censored,
                    "status": "skipped_insufficient_sample",
                }
            )
            continue

        try:
            splits = make_cv_splits(subset, args)
            _, cv_cindex = cross_validated_predictions(subset, spec, splits, args)
            rows.append(
                {
                    "model_step": spec.step,
                    "model": spec.name,
                    "n": subset.shape[0],
                    "n_events": events,
                    "n_censored": censored,
                    "cv_cindex": cv_cindex,
                    "status": "success",
                }
            )
        except Exception as exc:
            rows.append(
                {
                    "model_step": spec.step,
                    "model": spec.name,
                    "n": subset.shape[0],
                    "n_events": events,
                    "n_censored": censored,
                    "status": "failed",
                    "message": str(exc),
                }
            )

    return pd.DataFrame(rows)


def main() -> None:
    args = parse_args()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    log("============================================================")
    log("ADNI CN-to-MCI/AD cumulative biomarker survival analysis")
    log("Order: Age+Sex -> amyloid -> tau -> SPARE-BA -> SPARE-AD -> AD EPOCH")
    log("Primary sample: common complete cases across all cumulative steps")
    log("============================================================")

    data, qc, raw_predictions = prepare_analysis_dataset(args)
    specs = make_model_specs(args)
    common, all_predictors = validate_common_cohort(data, specs, args)

    data_path = outdir / f"{args.prefix}_baseline_analysis_dataset.tsv"
    common_path = outdir / f"{args.prefix}_common_complete_case_dataset.tsv"
    qc_path = outdir / f"{args.prefix}_biomarker_matching_qc.tsv"

    data.to_csv(data_path, sep="\t", index=False)
    common.to_csv(common_path, sep="\t", index=False)
    qc.to_csv(qc_path, sep="\t", index=False)

    variables = list(dict.fromkeys(all_predictors))
    missingness = pd.DataFrame(
        [
            {
                "variable": col,
                "present": col in data.columns,
                "n_total": data.shape[0],
                "n_nonmissing": int(data[col].notna().sum()) if col in data.columns else 0,
                "n_missing": int(data[col].isna().sum()) if col in data.columns else data.shape[0],
                "fraction_nonmissing": float(data[col].notna().mean()) if col in data.columns else 0.0,
            }
            for col in variables
        ]
    )
    missingness.to_csv(
        outdir / f"{args.prefix}_missingness.tsv",
        sep="\t",
        index=False,
    )

    sample_flow_rows = []
    for spec in specs:
        required = list(spec.predictors) + [args.time_col, args.event_col]
        if all(col in data.columns for col in required):
            subset = data.dropna(subset=required)
            sample_flow_rows.append(
                {
                    "model_step": spec.step,
                    "model": spec.name,
                    "required_predictors": ",".join(spec.predictors),
                    "maximum_complete_case_n_at_step": subset.shape[0],
                    "maximum_complete_case_events_at_step": int(subset[args.event_col].sum()),
                    "primary_common_complete_case_n": common.shape[0],
                    "primary_common_complete_case_events": int(common[args.event_col].sum()),
                }
            )
    pd.DataFrame(sample_flow_rows).to_csv(
        outdir / f"{args.prefix}_sample_flow.tsv",
        sep="\t",
        index=False,
    )

    results = run_common_cumulative_analysis(common, specs, args)
    for name, table in results.items():
        table.to_csv(
            outdir / f"{args.prefix}_{name}.tsv",
            sep="\t",
            index=False,
        )

    if args.allow_stage_specific_samples:
        secondary = run_stage_specific_secondary(data, specs, args)
        secondary.to_csv(
            outdir / f"{args.prefix}_stage_specific_secondary.tsv",
            sep="\t",
            index=False,
        )

    csf_cols = [args.amyloid_col] + parse_list(args.tau_cols)
    timing_summary_rows = []
    for marker in csf_cols:
        timing_col = f"{marker}_timing"
        if timing_col in qc.columns:
            counts = qc[timing_col].fillna("missing").value_counts(dropna=False)
            for timing, count in counts.items():
                timing_summary_rows.append(
                    {
                        "marker": marker,
                        "timing_relative_to_baseline": timing,
                        "n": int(count),
                    }
                )
    pd.DataFrame(timing_summary_rows).to_csv(
        outdir / f"{args.prefix}_first_csf_timing_summary.tsv",
        sep="\t",
        index=False,
    )

    summary = {
        "epoch_predictions_file": str(args.epoch_predictions_file),
        "adni_file": str(args.adni_file),
        "outcome": "First MCI or AD diagnosis after selected baseline-CN MRI",
        "full_prediction_sample_n": int(data.shape[0]),
        "full_prediction_sample_events": int(data[args.event_col].sum()),
        "common_complete_case_n": int(common.shape[0]),
        "common_complete_case_events": int(common[args.event_col].sum()),
        "common_complete_case_censored": int(common.shape[0] - common[args.event_col].sum()),
        "baseline_model": [args.age_col, args.sex_col],
        "cumulative_order": [
            args.amyloid_col,
            *parse_list(args.tau_cols),
            args.spare_ba_col,
            args.spare_ad_col,
            args.epoch_col,
        ],
        "csf_selection_rule": (
            "First chronologically available nonmissing measurement per participant and marker; "
            "measurements may occur before or after the baseline MRI, with timing retained in QC."
        ),
        "primary_comparison_rule": (
            "All nested models fit on one common complete-case cohort to permit paired incremental comparisons."
        ),
        "uses_all_original_model_splits": True,
        "baseline_cognition_included": False,
        "cv_folds_requested": args.cv_folds,
        "bootstrap_requested": args.bootstrap,
        "cox_penalizer_requested": args.cox_penalizer,
        "primary_performance_file": str(outdir / f"{args.prefix}_performance.tsv"),
        "primary_comparison_file": str(outdir / f"{args.prefix}_cumulative_comparisons.tsv"),
    }

    with open(outdir / f"{args.prefix}_summary.json", "w") as handle:
        json.dump(summary, handle, indent=2)

    log(f"Full baseline prediction cohort: N={data.shape[0]}, events={int(data[args.event_col].sum())}")
    log(
        "Common complete-case cohort: "
        f"N={common.shape[0]}, events={int(common[args.event_col].sum())}, "
        f"censored={int(common.shape[0] - common[args.event_col].sum())}"
    )
    log("Cumulative model performance:")
    log(
        results["performance"][
            ["model_step", "model", "n", "n_events", "cv_cindex", "apparent_cindex"]
        ].to_string(index=False)
    )
    log("Incremental comparisons:")
    log(
        results["cumulative_comparisons"][
            [
                "step",
                "added_block",
                "delta_cv_cindex",
                "delta_cv_cindex_ci_lower",
                "delta_cv_cindex_ci_upper",
                "bootstrap_p_two_sided",
                "likelihood_ratio_p",
            ]
        ].to_string(index=False)
    )
    log("============================================================")
    log(f"Analysis dataset: {data_path}")
    log(f"Common complete-case dataset: {common_path}")
    log(f"Performance: {outdir / f'{args.prefix}_performance.tsv'}")
    log(f"Comparisons: {outdir / f'{args.prefix}_cumulative_comparisons.tsv'}")
    log("============================================================")


if __name__ == "__main__":
    main()
